### ISSUE TITLE
CSV Structure for SNS Bank

### ISSUE THREAD

**Issue by javydekoning** [DanielsWrath/YNABGoingDutch#10]
CSV from SNS Bank does not have headers. The format is like this: 

```
02-03-2019,NL01SNSB0123456789,,,,,,EUR,123.45,EUR,-1.23,02-03-2019,02-03-2019,1234,BEA,12345678,'1abcde/123456','Description',4
02-03-2019,NL01SNSB0123456789,,,,,,EUR,123.45,EUR,1.23,02-03-2019,02-03-2019,1234,BEA,12345678,'1abcde/123456','Description',4
```

**Missing Headers:**
![alt text](https://d1b6tx2agdphz5.cloudfront.net/sns-nl/attachment/2c0359a3-ac13-478d-8987-232288ff86f7.jpg "Headers SNS Bank CSV")

**Comment by DanielsWrath** [comment]
I know, I have the same problem with the ASN bank (same parent company I think). I fail to see why in god's name you'd create CSV files without headers for things like this. But yeah, I am thinking of a good solution to add support for headerless CSV files

**Comment by javydekoning** [comment]
What about a regex match on the first line / second column to ID the bank? Pseudo code:

`if ( line[0]["col"][1].match('NL\d{2}SNSB\d{10}') ) {'SNSBANK'}

**Comment by DanielsWrath** [comment]
Hmm could be a good idea. I'll look at it tomorrow!

**Comment by DanielsWrath** [comment]
So yeah, this is gonna take some time. I have to implement my own fileStreamer to handle both headerless and headered files, while still being able to recognize the bank 😞

**Comment by DanielsWrath** [comment]
@javydekoning Hey! It should be working now! Took me some time to create everything from scratch. Can you please test it with your SNS csv files?

**Comment by javydekoning** [comment]
Awesome, I'll test today

**Comment by javydekoning** [comment]
Almost correct Daniel. Problem is that there is no Payee for PIN transactions. "incasso" / "overboeking" looks correct. 

Suggested fix: if column 'D' is null, take the first part of column 'R' as payee.

**Example line:**
`02-03-2019,NL01SNSB0123456789,,,,,,EUR,123.01,EUR,-2.41,02-03-2019,02-03-2019,7903,BEA,81349482,'8kdvqh/684577','Kruidvat 7039         >AMSTERDAM 2.03.2019 17U21 KV009 SYD0M0   MCC:5331 Contactloze betaling',4`

**Comment by javydekoning** [comment]
Looks like all are split by '>', so if you could split that column and trim the trailing whitespace you can use it as payee

**Comment by DanielsWrath** [comment]
Hmm looks like this is a specific SNS/ASN issue. It is a shame that their CSV files are such a mess. I'll look into a solution. I dislike adding code which is very bank-specific. I'll update you. Thanks for the email btw

**Comment by DanielsWrath** [comment]
@javydekoning I have added the extra fallback for asn and sns bank, when it comes to dealing with MCC payments 👌
