### ISSUE TITLE
Rabobank creditcard support

### ISSUE THREAD

**Issue by Gangleider** [DanielsWrath/YNABGoingDutch#23]
It would be nice if compatibility for Rabo credit cards was added at some point in the future, currently the CSV files are not recognized.

Example CSV structure:
>Creditcard Nummer,Munt,Productnaam,Creditcard Regel1,Creditcard Regel2,Transactie Referentie,Datum,Bedrag,Tegenrekening IBAN/BBAN,Omschrijving,Oorspr bedrag,Oorspr munt,Koers
>1234,EUR,RaboCard,FIRST LAST,,2019-08-230000003,2019-08-23,-5.99,NL00RABO0123456789,amazon.nl LUX,,,
>1234,EUR,RaboCard,FIRST LAST,,2019-08-230000002,2019-08-23,+20.00,NL00RABO0123456789,INCASSO - VORIG OVERZICHT,,,
>1234,EUR,RaboCard,FIRST LAST,,2019-08-20SH00019,2019-08-20,-41.67,NL00RABO0123456789,PAYPAL *EXAMPLE LTD       35558566123  GBR,,,

**Comment by DanielsWrath** [comment]
You could try to edit the banks.json file in the repo. You can create a fork, add the bank and make a merge request.

**Comment by DanielsWrath** [comment]
old
