### ISSUE TITLE
Include IBAN in payee

### ISSUE THREAD

**Issue by PehrGit** [DanielsWrath/YNABGoingDutch#27]
Hi, 

My transactions often include those from one of my bank accounts to another (checking to savings, for instance). The payee in all cases is the same, my name, but the IBAN is different. It would be useful if the tool put the name **and** the IBAN in the payee field so that YNAB can automatically recognize which bank account to which to set the transfer.

Thanks a bunch for creating this useful tool :)

Edit: I'm talking about Rabobank in this case, but I suspect it would be applicable to other banks as well.

**Comment by DanielsWrath** [comment]
I'll look into it! Had the same problem with my ABN-AMRO and ASN as well.

**Comment by ThinkPadNL** [comment]
@DanielsWrath i changed this (and some other things) for myself. But i don't think it is clean enough to do a pull request ;-)
https://github.com/ThinkPadNL/YNABGoingDutch/commit/55ec8d713a3408fa54ce58194c2f9e09ecacb46f
https://github.com/ThinkPadNL/YNABGoingDutch/commit/3a8f2a8571fbba79e3e42b78c60227003cb781a2

@PehrGit Have a look at my commits to see how you could do this, maybe my code also works instant for Rabobank (i use ASN).

**Comment by DanielsWrath** [comment]
It is fixed in PR #28. So this issue can be closed. Thanks for thinking with us @ThinkPadNL 😃

**Comment by ThinkPadNL** [comment]
I just downloaded the repo, but it doesn't seem to have any effect on my ASN exports?
