### ISSUE TITLE
Add support for English BUNQ

### ISSUE THREAD

**Issue by MagicLegend** [DanielsWrath/YNABGoingDutch#36]
> Please state the bank name and the type of account you would like to be supported.
> It is important to add an __anonymized__ CSV file from the requested bank to your issue. You can add this file in a .zip.

Hi!

My Bunq is in English; so my exports are in English as well. The filled in JSON:

```json
  "bunq-en": {
    "bankName": "BUNQ-EN",
    "header": [
      "Date",
      "Interest Date",
      "Amount",
      "Account",
      "Counterparty",
      "Name",
      "Description"
    ],
    "account": [
      "Account"
    ],
    "date": [
      "Date"
    ],
    "dateFormat": "DD/MM/YYYY",
    "payee": [
      "Name",
      "Counterparty"
    ],
    "category": [],
    "memo": [
      "Description"
    ],
    "outflow": [
      "Amount"
    ],
    "inflow": [
      "Amount"
    ],
    "positiveIndicator": null,
    "negativeIndicator": "-"
  },
```

Edited English export:
[anon-bunq-export.zip](https://github.com/DanielsWrath/YNABGoingDutch/files/5006811/anon-bunq-export.zip)

Because of the possibility of conflicts between Dutch and English bunq exports, I have not attempted at making a PR for this. You know best how possible conflicts could be handled.

Thanks!

**Comment by DanielsWrath** [comment]
Thanks! As this BUNQ version had a different header, it should not create conflicts. Those would only appear when it cannot find a match with a header and uses the bankName in the IBAN instead (NLxxBUNQxxxxxxxxx). You can try to add it to the json and test it with both BUNQ files. If everything is alright you can make a PR.

I can also do it, but that might take some time.

**Comment by MagicLegend** [comment]
See #37
