### ISSUE TITLE
Date output broken (bunq)

### ISSUE THREAD

**Issue by Althestrasz** [DanielsWrath/YNABGoingDutch#43]
**Describe the bug**
On all bunq statements, the date field is corrupted and unusable when imported to YNAB. I initially considered the issue to be with the "recent" CSV changes of bunq with their new interest payments — the issue also persists with CSV files from 2018, long before the introduction

**To Reproduce**
1. Import recent bunq statement
2. Download CSV
3. Open downloaded CSV
4. Starting after the definitions (line 1), all transactions have a non-standard date formatting.

**Expected behavior**
Output transaction date to YYYY-MM-DD, instead output date is grarbled:
>"Date","Payee","Category","Memo","Outflow","Inflow"
>"20-1--3-26","NYTimes*NYTimes","","NYTimes*NYTimes 800-698-4637, US","2.00","0"`

Input:
>"Date","Interest Date","Amount","Account","Counterparty","Name","Description"
>"2021-03-26","2021-04-01","-2,00","NL98BUNQ2206754703","","NYTimes*NYTimes","NYTimes*NYTimes 800-698-4637, US"

**Console**
If applicable, add the console log to help explain your problem.

**Desktop (please complete the following information):**
 - OS: MacOS 11.3.1
 - Browser: Safari
 - Version: 14.1

**Additional context**
Issue not present with Rabobank statement.

**Comment by DanielsWrath** [comment]
Could you upload an input file? Copy pasting the input has shown to be error prone

**Comment by Althestrasz** [comment]
Here's an example:
[2021-05-17_11-03-45_bunq-statement.csv](https://github.com/DanielsWrath/YNABGoingDutch/files/6492649/2021-05-17_11-03-45_bunq-statement.csv)

**Comment by DanielsWrath** [comment]
Apparently the date config is not correct in the banks.json. It says DD/MM/YYYY, whereas your version is YYYY-MM-DD. Would you happen to know if bunq updated its date format in the CSV? Did the YNAB converter use to work before?

**Comment by DanielsWrath** [comment]
I've pushed the change. Please check if it is working now. Maybe I should build a check to verify the dateformat, to make sure that these errors can't occur.

**Comment by Althestrasz** [comment]
Verified, issue is resolved! Thanks! As for the dateformat checking, I assuming checking the first line of entries would be enough, but I am not sure how much overhead that would add.

**Comment by DanielsWrath** [comment]
Ah sorry missed that part! So should be fixed now then. Not sure why the date settings were wrong in the json. Probably some oversight from the committee.

> It also misses the parentheses in the file header line of the CSV.
What do you mean with that?

**Comment by Althestrasz** [comment]
Sorry, I realized I wrote parentheses but meant quotation marks. If you compare the bunq-en testfile to my submitted file, you noticed that the quotation marks are missing in the testfile.

**Comment by DanielsWrath** [comment]
Ah right! I will edit the test files then! Thanks for notifying me! 😄
