### ISSUE TITLE
Current ASN Bank csv format not recognised

### ISSUE THREAD

**Issue by etmjansen** [DanielsWrath/YNABGoingDutch#45]
**Describe the bug**
When trying to convert a downloaded csv file from ASB Bank Internet banking I get the error message 'Bank could not be recognised!'.

**To Reproduce**
1. Go to https://www.asnbank.nl
2. Login, click on bank account
3. Choose 'Transacties downloaden'
4. Select a time periode
5. Choose 'bestandsformaat' value 'CSV' or 'CSV2004'
6. Press the button 'Downloaden'
7. Clone this project and open Index.html in the browser
8. Drag the downloaded file into the box 
9. Get the error message 'Bank could not be recognised!'

**Expected behavior**
I gather after dragging and dropping the csv file I would get a prompt for a download of a converted file that is able to be imported into YouNeedABudget.

**Desktop (please complete the following information):**
 - OS: MacOSx BigSur 11.5.2
 - Browser Brave, Safari
 - Version Version 1.29.79 Chromium: 93.0.4577.63 (Official Build) (x86_64), Version 15.0 (16612.1.29.41.4, 16612)

**Comment by DanielsWrath** [comment]
I've recently converted ASN successfully, but not on my mac. So I'll try that for you

**Comment by DanielsWrath** [comment]
I cannot reproduce the problem you have with my own ASN bank statements (using my macOS big sur safari/chrome/firefox). Could you try using the [website](https://ynab.danielhaitink.nl). This is directly hosted by github using the code in the master branch, which you can find in deployments of this repo. You can also visit [danielswrath.github.io/YNABGoingDutch/](danielswrath.github.io/YNABGoingDutch/), which will redirect you to my CNAME at my own domain.

Are you sure that you are hosting the master branch at your own PC while running the site locally?

**Comment by etmjansen** [comment]
Hi Daniel. I tried with the hosted website and your own domain version and both work.

As I indicated in the steps I cloned the master branch locally. Opened up Brave and opened the index.html file in it.

I have not ran a web server locally like for instance IIS or Apache to host the files. I guess that is needed gathering from your question?

**Comment by DanielsWrath** [comment]
Looks like a problem with accessing the json file. Seems like it is now necessary to host the site locally on a server. See [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp)
