### ISSUE TITLE
Update YNAB account selection in dialog

### ISSUE THREAD

**Issue by Althestrasz** [DanielsWrath/YNABGoingDutch#59]
**Current selection and issue**
The selection pop-up currently shows all YNAB accounts, even if they are closed (archived), tracking or loan accounts.
They are shown in the order of JSON response, but otherwise not sorted based on any status or category. This means that the list is cluttered, especially if you have many closed YNAB accounts.

**Describe the solution you'd like**
While I believe all YNAB accounts should be visible, their status should be used to streamline the account selection. The JSON response for each account includes two variables that can help with this:  `"on_budget"` and `"closed"`
Then using `<optgroup>`-tags, the `<select>`-element can be easily stylized. 

**HTML example**
```
<div id="selection-popup">
<p>Which account for NL99YNAB0001234567</p>
<select>
 <!—For YNAB accounts that have "on_budget": true, "closed": false,-->
<optgroup label="On Budget Accounts"> 
	<option value="0">Regular</option>
	<option value="1">Saving</option>
	<option value="2">Emergency Fund</option>
	<option value="3">Family Account</option>
</optgroup>
 <!—For YNAB accounts that have "on_budget": false, "closed": false,-->
<optgroup label="Tracking Accounts">
	<option value="4">Stocks</option>
	<option value="5">OV Chipcard</option>
</optgroup>
<!—For YNAB accounts that have "closed": true,-->
<optgroup label="Closed Accounts">
	<option value="6">Student Loan</option>
	<option value="7">DNB account</option>
</optgroup>
</select>
	<button class="button-border">cancel</button>
	<button class="button-border">accept</button>
</div>
```

**Comment by DanielsWrath** [comment]
Should be added in the master branch!
