### ISSUE TITLE
ING transaction date vs processed date

### ISSUE THREAD

**Issue by MPaans** [DanielsWrath/YNABGoingDutch#8]
ING has a discrepancy between actual transaction dates and the date the transaction is processed. For example, if you paid for something on january 1st, it might not get processed till january 3rd due to business days. Card payments have a transaction date in "Mededelingen" under the subfield "Pasvolgnr". However, I can't quite seem to find an entrypoint to scoop out the transaction date from "Mededelingen". I've been trying something like this on line 260:

`date: new INGTransactionDate(new Field(["Mededelingen"], ['Pasvolgnr'], ['Pasvolgnr'])) || new Field(["Datum"]),`

And feed it to INGTransactionDate() to process it (I simply need to extract the date with some regexp magic and return it). But it doesn't return a string (variable "text" in the getLine method in Field) as one would expect. Got any clues how to proceed?

**Comment by DanielsWrath** [comment]
I'd rather not have Bank specific code in my system though. I want to create a .json in the future which contains configuration for all the banks. However there are probably ways to do this. Can you maybe send an example of how this looks like in ING? 

Please edit out all the personal info 😄

**Comment by MPaans** [comment]
This is a line from a ING CSV:
`"20180813","YOURCASH NLD","NL40INGB0123456789","","GM","Af","12,34","Geldautomaat","Pasvolgnr:010 10-08-2018 12:34 Transactie:12X3Y4 Term:AB1234"`

I already made some improvements after looking at the code with a fresh pair of eyes. Should I do another pull request? I pushed everything to master, should I create a branch first?

**Comment by DanielsWrath** [comment]
I think it would be preferable if you implement the feature as a whole and then create a pull request. Or you can create a pull request to develop and then I can merge that into master at some point
